# Generated by Django 3.0.5 on 2020-05-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.ImageField(default=1, upload_to='photos/', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
